;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
+GameplayTagList=(Tag="RooGame",DevComment="Stats Designer namespace root")
+GameplayTagList=(Tag="RooGame.Stats",DevComment="Stats root")
+GameplayTagList=(Tag="RooGame.Stats.Attribute",DevComment="Attributes root")
+GameplayTagList=(Tag="RooGame.Stats.Stat",DevComment="Stats root")
+GameplayTagList=(Tag="RooGame.Stats.Attribute.HP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Attribute.MP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.MaxHP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.MaxMP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Attack",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Defense",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Level",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.CurrentEXP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.MaxEXP",DevComment="")

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="RooGame.Stats.Attribute.HP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Attribute.MP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Attack",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.CurrentEXP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Defense",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Exp",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Level",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.MaxEXP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.MaxHP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.MaxMP",DevComment="")

