;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
+GameplayTagList=(Tag="RooGame",DevComment="Stats Designer namespace root")
+GameplayTagList=(Tag="RooGame.Stats",DevComment="Stats root")
+GameplayTagList=(Tag="RooGame.Stats.Attribute",DevComment="Attributes root")
+GameplayTagList=(Tag="RooGame.Stats.Stat",DevComment="Stats root")
+GameplayTagList=(Tag="RooGame.Stats.Attribute.HP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Attribute.MP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.MaxHP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.MaxMP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Attack",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Defense",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Level",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.CurrentEXP",DevComment="")
+GameplayTagList=(Tag="RooGame.Stats.Stat.MaxEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame",DevComment="Stats Designer namespace root")
+GameplayTagList=(Tag="MyRPGGame.Stats",DevComment="Stats root")
+GameplayTagList=(Tag="MyRPGGame.Stats.Attribute",DevComment="Attributes root")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat",DevComment="Stats root")
+GameplayTagList=(Tag="MyRPGGame.Formula",DevComment="Formula root")
+GameplayTagList=(Tag="MyRPGGame.Table",DevComment="Table root")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect",DevComment="Status Effect root")
+GameplayTagList=(Tag="RooGame.Stats.Stat.Exp",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Attribute.HP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Attribute.MP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Attack",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Defense",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Level",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MaxHP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MaxMP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.EXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.CurrentEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MaxEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Character.RPGPlayer",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Character.RPGEnemy",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.BaseFlat",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.BasePercent",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.FinalFlat",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.FinalPercent",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.Attack.BasicAttack",DevComment="")

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16

